CREATE TABLE IF NOT EXISTS organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    role_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_org FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE IF NOT EXISTS asset_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_asset_category_org FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT uk_asset_category_org_name UNIQUE (organization_id, name)
);

CREATE TABLE IF NOT EXISTS asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    category_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    image_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_asset_org FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES asset_category (id)
);

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    approved_by_id BIGINT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    checked_in_at TIMESTAMP,
    checked_out_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_booking_org FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_booking_asset FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_booking_approved_by FOREIGN KEY (approved_by_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS maintenance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    created_by_id BIGINT,
    description TEXT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_maintenance_org FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_maintenance_asset FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_maintenance_created_by FOREIGN KEY (created_by_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    organization_id BIGINT,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    details JSONB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_audit_org FOREIGN KEY (organization_id) REFERENCES organization (id)
);

CREATE INDEX IF NOT EXISTS idx_user_org_id ON "user" (organization_id);
CREATE INDEX IF NOT EXISTS idx_user_role_id ON "user" (role_id);
CREATE INDEX IF NOT EXISTS idx_asset_org_id ON asset (organization_id);
CREATE INDEX IF NOT EXISTS idx_asset_category_id ON asset (category_id);
CREATE INDEX IF NOT EXISTS idx_booking_org_id ON booking (organization_id);
CREATE INDEX IF NOT EXISTS idx_booking_asset_id ON booking (asset_id);
CREATE INDEX IF NOT EXISTS idx_booking_user_id ON booking (user_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON booking (status);
CREATE INDEX IF NOT EXISTS idx_maintenance_org_id ON maintenance_record (organization_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_asset_id ON maintenance_record (asset_id);
CREATE INDEX IF NOT EXISTS idx_audit_org_id ON audit_log (organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_user_id ON audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_log (created_at);
